<div id="header">
  <nav>
    <ul class="nav">
      <li><a href="../index.php">Inicio</a></li>
      <li>
        <a href="./catalogo.php">Catálogo</a>
        <ul>
          <li><a href="./catalogo.php">Insertar</a></li>
          <li><a href="./FormDEL.php">Eliminar</a></li>
          <li><a href="./FormMOD.php">Modificar</a></li>
        </ul>
      </li>
      <li>
        <a href="./consultas.php">Consultas</a>
        <ul>
          <li><a href="">Ingresos</a></li>
          <li><a href="./pages/consultas.php">Egresos</a></li>
          <li><a href="">Ahorro</a></li>
          <li><a href="">Totales</a></li>
        </ul>
      </li>
      <li><a href="../logout.php">Log Out</a></li>
    </ul>
  </nav>
</div>
