<div class="botones">
    <button type="button" class="botonesMenu" onclick="window.location.href='../index.php'">Inicio</button>
    <button type="button" class="botonesMenu" onclick="window.location.href='../Pages/catalogo.php'">Catálogo</button>
    <button type="button" class="botonesMenu" onclick="window.location.href='../Pages/consultas.php'">Consultas</button>
    <button type="button" class="logOut"      onclick="window.location.href='../logout.php'">Log Out</button>
</div>