<div class="tableFooter">
<input type="button" class="bn632-hover bn19" value="Mostrar Total" onclick="SetBox('total')" />
                        <div id="total">
                            <?php
                            if ($total !== 0) {
                                echo $total;
                            }
                            ?>
                        </div>
                    </div>