<div class="contenedor">
        <div class="main_box">
            <input type="checkbox" id="check">
            <div class="btn_one">
                <label for="check">
                    <i class="fas fa-bars"></i>
                </label>
            </div>
            <div class="sidebar_menu">
                <div class="logo">
                    <a href="#">Gestión</a>
                </div>
                <div class="btn_two">
                    <label for="check">
                        <i class="fas fa-times"></i>
                    </label>
                </div>
                <div class="menu">
                    <ul>
                        <li><i class="fas fa-qrcode"></i>
                            <a href="../index.php">Inicio</a>
                        </li>
                        <li>
                            <i class="far fa-newspaper"></i>
                            <a href="./catalogo.php">Catálogo</a>
                            <ul>
                                <li>
                                    <i class="fas fa-plus"></i>
                                    <a href="./catalogo.php">Añadir</a>
                                </li>
                                <li>
                                    <i class="fas fa-minus"></i>
                                    <a href="./FormDEL.php">Quitar</a>
                                </li>
                                <li>
                                    <i class="fas fa-exchange-alt"></i>
                                    <a href="./FormMOD.php">Modificar</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <i class="far fa-question-circle"></i>
                            <a href="./consultas.php">Consultas</a>
                            <ul>
                                <li>
                                    <i class="fas fa-plus"></i>
                                    <a href="./consultas.php">Egresos Pasados</a>
                                </li>
                                <li>
                                    <i class="fas fa-minus"></i>
                                    <a href="./consultas.php">Egresos Futuros</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <i class="fas fa-sign-out-alt"></i>
                            <a href="../logout.php">LogOut</a>
                        </li>
                    </ul>
                    </li>
                </div>
            </div>